### ISSUE TITLE
Конструкторы

### ISSUE THREAD

**Issue by KayAltos9104** [XPYCT1/-#10]
В будущем начальные характеристики лучше сделать в конструкторе, а не через вызов полей. 
```
Student student1 = new Student();
        student1.Health = x;
        student1.Intelligence = y;
        student1.Happiness = z;
        student1.Knowledge = w;
```

**Comment by XPYCT1** [comment]
В плане в конструкторе? 
student1.Health = 100;
Так или как-то иначе,не до конца понял

**Comment by KayAltos9104** [comment]
Повторите лекцию про классы, я там рассказываю, что у класса есть конструкторы, особые функции, которые позволяют сделать экземпляр сразу с заданными значениями без необходимости отдельно писать это все при создании
