### ISSUE TITLE
Переменные должны иметь осмысленные названия

### ISSUE THREAD

**Issue by KayAltos9104** [XPYCT1/-#9]
Я это уже говорил)
`int x, y, z, w;`
Вот так не нужно))

**Comment by XPYCT1** [comment]
Писать
int x;
int y;
int z;
или сами буквы плохие?

**Comment by KayAltos9104** [comment]
Писать что там хранится. Если вы туда с консоли записываете здоровье, то 
int inputHealth, например. Я же говорил - по названию переменной должно быть понятно, что в ней хранится
